Edited Welcome's Broadcast (for new players)
SpigotMC/SpigotCraft pull request #387
Opened 2018-03-19 19:29 UTC by x9nico

2018-03-19 19:53 UTC, MiniDigger requested changes

2018-03-19 19:53 UTC, MiniDigger commented on plugins/Essentials/config.yml
> +  announce-format: '&dWelcome {DISPLAYNAME}&d to SpigotCraft server!'
this doesn't make sense grammatically, either 'to the server' or 'to the SpigotCraft server', not just 'to SpigotCraft server'

2018-03-19 20:08 UTC, MiniDigger approved these changes

2018-03-19 23:48 UTC, yannicklamprecht approved these changes

2018-03-22 22:48 UTC, 28andrew approved these changes

2018-03-26 04:36 UTC, merged